### ISSUE TITLE
deepstream staticdev QA Issue

### ISSUE THREAD

**Issue by aurelien-enchanted-tools** [OE4T/meta-tegra-community#102]
Hello,

On mickledore and kirkstone, I obtain the following issue:
```
ERROR: deepstream-6.3-6.3.0-1-r0 do_package_qa: QA Issue: non -staticdev package contains static .a library: deepstream-6.3 path '/usr/lib/gstreamer-1.0/deepstream/libnvdsgst_multistream_legacy.a' [staticdev]
ERROR: deepstream-6.3-6.3.0-1-r0 do_package_qa: Fatal QA errors were found, failing task.
```
I found a workaround: add ${PN}-staticdev in the PACKAGES list to solve the issue.

**Comment by madisongh** [comment]
Not sure how I missed that, thanks.  The fix is now in master, and I've back-ported it to mickledore and kirkstone.
