### ISSUE TITLE
deepstream gstreamer plugin for V4L2 jpeg decoder 

### ISSUE THREAD

**Issue by bchoineubility** [OE4T/meta-tegra-community#104]
Hi,

I am testing with deepstream with gstream plugin but, following code is return NULL. 

` gst_element_factory_make("nvv4l2decoder", jpeg_decoder_name.c_str());`

I think deepstream of yocto version would not include plugin.

Can you please let me know deepstream of yocto version support all gstreamer plugins as well?

BR,
Mark

**Comment by dwalkes** [comment]
Hi Mark,

The nvv4l2decoder is tested with the [sintel test](https://github.com/OE4T/meta-tegra-community/blob/d6777fb011a1fad9c146c7b3fc573e4827262292/recipes-test/tegra-tests/gstreamer-tests/sinteltest.sh.in#L7 ) as a part of the gstreamer-tests package.  You can find the combinations we've tested with tegra-demo-distro on the [Releases Validation Sheet](https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit#gid=574448205).

You'll need to include the [gstreamer1.0-plugins-nvvideo4linux2](https://github.com/OE4T/meta-tegra/tree/524bf0c79c2ae2549830367be373e9e01167084b/recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2-1.14.0-r35.4.1) recipe, which in included in [gstreamer-1.0-plugins-tegra](https://github.com/OE4T/meta-tegra/blob/524bf0c79c2ae2549830367be373e9e01167084b/recipes-multimedia/gstreamer/gstreamer1.0-plugins-tegra_1.14.0-r35.4.1.bb).

You may want to test drive the [tegra-demo-distro](https://github.com/OE4T/tegra-demo-distro) `demo-image-full` image for the corresponding `MACHINE` and use this to compare to your image content.

**Comment by bchoineubility** [comment]
Hi dwalks,

Thanks for reply.

I will look over it.

BR,
Mark

**Comment by dwalkes** [comment]
Hi Mark
That's correct, this is not formal QA and we don't test everything.  It's the effort of volunteers attempting to ensure we have some coverage of major components between releases.  Any help in additional coverage is welcome and appreciated.  Request edit access on the sheet if you'd like to make changes.

**Comment by dwalkes** [comment]
Did you try with `tegra-demo-distro` and image `demo-image-full`?  If so, which branch are you using?

**Comment by bchoineubility** [comment]
I don't use tegra-demo-distro layer now. sintel_test and gstreamer can be accessed only with sudo now.

I added a new user account and give the new user sudo access to test my applications. these application are running well on the nvidia ubuntu system. 

Is there any information that i will give you more?

I will loot into tegra-demo-distro to find a hint.

**Comment by bchoineubility** [comment]
Hi Dan,

I found libgstnvvideo4linux2 is in the black list.

when I run the command:
`gst-inspect-1.0 -b`

I can get the black list. I am not sure why they are in the blacklist for my new account.

`
[[33mBlacklisted files:[[0m
  libcustom2d_preprocess.so
  libgstnvarguscamerasrc.so
  libgstnvcompositor.so
  libgstnvdrmvideosink.so
  libgstnvivafilter.so
  libgstnvv4l2camerasrc.so
  libgstnvvidconv.so
  libgstnvvideo4linux2.so
  libgstnvvideoconvert.so
  libnvdsgst_deepstream_bins.so
  libnvdsgst_dewarper.so
  libnvdsgst_dsexample.so
  libnvdsgst_infer.so
  libnvdsgst_multistream.so
  libnvdsgst_multistreamtiler.so
  libnvdsgst_preprocess.so
  libnvdsgst_tracker.so

[[94mTotal count[[0m: [[0m17 blacklisted files[[0m
`
Can you let me know how to resolve it?

BR,
Mark

**Comment by madisongh** [comment]
> I added a new user account and give the new user sudo access to test my applications. these application are running well on the nvidia ubuntu system.

Generally, if something works when run as root (or under sudo), but not under another user account, you have a permissions problem.  Check the list of groups for the user account you added.  At the very least, users need to be in the `video` group to access the video-related devices exported by the NVIDIA drivers.

**Comment by bchoineubility** [comment]
Hi Matt,

Even I tried to add all groups listed in the /etc/groups, it does not work.

Looking into device files in the /dev have no permission and group for **video** and trying to change permission and owner of group to 660 and video respectly. then, error message is changing to 

```
jetson-agx-xavier-devkit:~/.cache/gstreamer-1.0$ gst-inspect-1.0
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
nvbufsurftransform:cuInit failed : 999
libnvrm_gpu.so: NvRmGpuLibOpen failed, error=196624
```

It means non-root user do not access nvidia driver node. 

How can  I resolve it ? 


BR,
Mark

**Comment by madisongh** [comment]
I don't know what's gone wrong in your setup, but it is certainly possible to configure your system to have processes run as non-root users and still have access to the GPU and other video hardware.  I've done so in several projects; NVIDIA sets this up in their JetPack/Jetson Linux Ubuntu also.

For troubleshooting, you might want to try running your program under `strace` for the working and non-working cases and compare the output between the two to see what's different.

**Comment by bchoineubility** [comment]
I think this issue is coming from : 

- all ownership and access right for nvidia device nodes undeer /dev is tied to root and access right is 600. 
- they have no group ownership for **video** also.
- so non-root user can not access those device with gstreamer plugin access those device nodes under /dev.

I am not sure above issues have been in the this distribution or my setup have occurred.

I hope you doubly check you can run **gst-inspect** and see block list as non-root user for gstreamer nvidia plugins are not in your target system.

BR,
Mark

**Comment by bchoineubility** [comment]
Hi Matt,

I doubly check permission and ownership in the other yocto box which I brought up 4 months ago and do not particular custom setup in the local.conf, but, it also show the same permission and ownership for /dev.

```
drwxr-xr-x  3 root root          60 Apr 28  2022 nvgpu
crw-------  1 root root    505,   0 Aug  3 04:18 nvhost-as-gpu
crw-------  1 root root    507,   0 Aug  3 04:18 nvhost-ctrl
crw-------  1 root root    505,   2 Aug  3 04:18 nvhost-ctrl-gpu
crw-------  1 root root    507,  66 Aug  3 04:18 nvhost-ctrl-isp
crw-------  1 root root    507,  18 Aug  3 04:18 nvhost-ctrl-nvdec
crw-------  1 root root    507,  22 Aug  3 04:18 nvhost-ctrl-nvdec1
crw-------  1 root root    507,  54 Aug  3 04:18 nvhost-ctrl-nvdla0
crw-------  1 root root    507,  58 Aug  3 04:18 nvhost-ctrl-nvdla1
crw-------  1 root root    507,  46 Aug  3 04:18 nvhost-ctrl-pva0
crw-------  1 root root    507,  50 Aug  3 04:18 nvhost-ctrl-pva1
crw-------  1 root root    505,   3 Aug  3 04:18 nvhost-ctxsw-gpu
crw-------  1 root root    505,   4 Aug  3 04:18 nvhost-dbg-gpu
crw-------  1 root root    505,   1 Aug  3 04:18 nvhost-gpu
crw-------  1 root root    507,  65 Aug  3 04:18 nvhost-isp
crw-------  1 root root    507,  41 Aug  3 04:18 nvhost-isp-thi
crw-------  1 root root    507,   9 Aug  3 04:18 nvhost-msenc
crw-------  1 root root    507,  33 Aug  3 04:18 nvhost-nvcsi
crw-------  1 root root    507,  17 Aug  3 04:18 nvhost-nvdec
crw-------  1 root root    507,  21 Aug  3 04:18 nvhost-nvdec1
crw-------  1 root root    507,  53 Aug  3 04:18 nvhost-nvdla0
crw-------  1 root root    507,  57 Aug  3 04:18 nvhost-nvdla1
crw-------  1 root root    507,  13 Aug  3 04:18 nvhost-nvenc1
crw-------  1 root root    507,   5 Aug  3 04:18 nvhost-nvjpg
crw-------  1 root root    505,   9 Aug  3 04:18 nvhost-nvsched-gpu
crw-------  1 root root    506,   0 Aug  3 04:18 nvhost-power-gpu
crw-------  1 root root    505,   6 Aug  3 04:18 nvhost-prof-ctx-gpu
crw-------  1 root root    505,   7 Aug  3 04:18 nvhost-prof-dev-gpu
crw-------  1 root root    505,   5 Aug  3 04:18 nvhost-prof-gpu
crw-------  1 root root    507,  45 Aug  3 04:18 nvhost-pva0
crw-------  1 root root    507,  49 Aug  3 04:18 nvhost-pva1
crw-------  1 root root    505,   8 Aug  3 04:18 nvhost-sched-gpu
crw-------  1 root root    507,  61 Aug  3 04:18 nvhost-slvs-ec
crw-------  1 root root    507,  25 Aug  3 04:18 nvhost-tsec
crw-------  1 root root    507,  29 Aug  3 04:18 nvhost-tsecb
crw-------  1 root root    505,  10 Aug  3 04:18 nvhost-tsg-gpu
crw-------  1 root root    507,  69 Aug  3 04:18 nvhost-vi
crw-------  1 root root    507,  37 Aug  3 04:18 nvhost-vi-thi
crw-------  1 root root    507,   1 Aug  3 04:18 nvhost-vic
crw-------  1 root root     10,  54 Aug  3 04:18 nvmap
crw-------  1 root root    234,   0 Aug  3 04:18 nvme0
brw-rw----  1 root disk    259,   0 Aug  3 04:18 nvme0n1
crw-------  1 root root    235,   0 Aug  3 04:18 nvsciipc
```

I don't understand permission and owner ship will change as local.conf  because I think device nodes are created /dev/ in the root file system when build root file system.

I doubt those mechanism would be different between yocto and Ubuntu. 

I think the working it by changing permission with `sudo chmod -R 777 /dev` seems that this issue is coming from permission and ownership for non-root user.

BR,
Mark.

**Comment by bchoineubility** [comment]
I found core-image-sato image correct permission and ownership after rebuild it.

Actually, I have used ros-image-world image and it would occur this issue.

I closed this issue.

Thanksm Matt and Dan.

BR,
Mark
