### ISSUE TITLE
python3-jetson-stats: update for JP6 compatibility 

### ISSUE THREAD

**Issue by chamois94** [OE4T/meta-tegra-community#129]
Hello, 

The current 4.2.3 version of python3-jetson-stats is not compatible with JP6.0.

Do you plan to update version to the latest one ?

Thanks

**Comment by chamois94** [comment]
The latest version is 4.2.12 which is tagged compatible with jp6.0 and JP 6.1. why did you chose 4.2.4 which is only compatible with jp6 DP ?

**Comment by spencercw** [comment]
4.2.4 is the most recent version on the [GitHub releases page](https://github.com/rbonghi/jetson_stats/releases). Did not see that there are other more recent versions in the tags. Not sure why they've done it this way.

**Comment by ichergui** [comment]
> The latest version is 4.2.12 which is tagged compatible with jp6.0 and JP 6.1. why did you chose 4.2.4 which is only compatible with jp6 DP ?

Hi @chamois94 
Do you have any issue ? If so, create one here and I will take care of it.
I didn't understand your question.
