### ISSUE TITLE
file /usr/bin/.debug/openssl conflicts between attempted installs of openssl-dbg-3.0.2-r0.armv8a and openssl111-dbg-1.1.1l-r0.armv8a

### ISSUE THREAD

**Issue by jackatparallel** [OE4T/meta-tegra-community#26]
Hey all, thanks for putting out this layer! 

Currently trying to build a Yocto `kirkstone` distro using your `deepstream-6.0_6.0.1-1.bb` recipe, but encountering issues with `openssl111` conflicting with the OpenSSL version shipped with Yocto. While trying to build our development image, I get the following error during `do_rootfs`:

```
Error: Transaction test error:
  file /usr/bin/.debug/openssl conflicts between attempted installs of openssl-dbg-3.0.2-r0.armv8a and openssl111-dbg-1.1.1l-r0.armv8a
```

In our dev image's `.bb` file, I have `EXTRA_IMAGE_FEATURES +=  "... dbg-pkgs ..."` - removing `dbg-pkgs` from `EXTRA_IMAGE_FEATURES` allows the whole image to compile.

What's the best fix here? We need to keep `dbg-pkgs` enabled - is there a good way to rename the `/usr/bin/.debug/openssl` debug file from `openssl111` to something like `/usr/bin/.debug/openssl111`? Thanks

**Comment by madisongh** [comment]
Hmm. The best answer is probably to modify the `do_install` function in the recipe to rename the programs installed into `${bindir}` to have a `-.1.1.1` suffix so the names don't conflict with the openssl 3 copies.  That will avoid conflicts in the `-bin` package, and should fix the problem with the `-dbg` package as well.

**Comment by jackatparallel** [comment]
Great, thank you

**Comment by madisongh** [comment]
I've pushed a fix with the suffix addition to the master and kirkstone branches.
