### ISSUE TITLE
Build issue for python3-jetson-stats on Ubuntu 20.04

### ISSUE THREAD

**Issue by sakoman** [OE4T/meta-tegra-community#40]
Error is:

ERROR: 'python3 setup.py bdist_wheel ' execution failed

Issue can be fixed by inheriting setuptools3_legacy instead of setuptools3

Note from setuptools3_legacy class:

 This class is for packages which use the deprecated setuptools behaviour,
 specifically custom install tasks which don't work correctly with bdist_wheel.
 This behaviour is deprecated in setuptools[1] and won't work in the future, so
 all users of this should consider their options: pure Python modules can use a
 modern Python tool such as build[2], or packages which are doing more (such as
 installing init scripts) should use a fully-featured build system such as Meson.

 [1] https://setuptools.pypa.io/en/latest/history.html#id142
 [2] https://pypi.org/project/build/

**Comment by ichergui** [comment]
Hello @sakoman 
Thanks for sharing this. I will take a look.
I will keep you update  when having the adequate solution
